version: '3'
services:
  backend:
    build: ./backend
    container_name: backend
    tty: true
    stdin_open: true
    restart: always
    command: npm run dev
    volumes:
      - ./backend:/app
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: root
      DB_PASSWORD: '123456'
      JWT_SECRET: secret
    ports:
      - "3001:3001"
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: '123456'
      POSTGRES_DB: postgres
    ports:
    - "5432:5432"